logging:
  level: 
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %p [%F:%L] %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %p [%F:%L] %m%n"
  file: D://logs/hyb-${spring.application.name}.log
eureka:
  instance:
    prefer-ip-address: true                       # 设置微服务调用地址为IP优先（缺省为false）
    lease-renewal-interval-in-seconds: 5          # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15      # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
