spring:
  cloud:
    gateway:
      default-filters:
      routes:
      #------------------------------------------------------------------------
      - id: pay
        uri: lb://pay
        predicates:
        - Path= /pay/**
        filters:
        - StripPrefix= 1
      #------------------------------------------------------------------------
      - id: message
        uri: lb://message
        predicates:
        - Path= /message/**
        filters:
        - StripPrefix= 1
