server:
  port: 9001
spring:
  data:
    mongodb:
      uri: mongodb://test_0:Xian62Mongo_test@dds-bp17964b8ebb26941.mongodb.rds.aliyuncs.com:3717,dds-bp17964b8ebb26942.mongodb.rds.aliyuncs.com:3717/test_0?replicaSet=mgset-3016261
  redis:
    database: 0
    host: hyb-test-vm00.huayingbaolicai.com
    port: 6379
    password: null
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000
